### ISSUE TITLE
Investigate background refreshing of hostname in caching host resolver

### ISSUE THREAD

**Issue by BrandonArp** [ArpNetworking/commons#31]
Hostname lookup uses reverse DNS lookups.  Ideally, a host's name for the local IP is in /etc/hosts (or OS-specific equivalent), but that's not always the case.  In the case that it's missing, the network DNS server will be contacted for the hostname.  The default timeout for DNS lookups is very long (up to 30 seconds by default).  This could lead to incredibly long blocking calls where they are not expected.

To remedy the issue, investigate using a background refreshing mechanism for the caching host resolver.

**Comment by vjkoskela** [comment]
This was resolved with #32.
